### ISSUE TITLE
Syncing the pool

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo-mining-pool#1]
I was able to setup the mining pool and mine remotely.

The mining pool document says something like the pool runs a full node. Is there a procedure to syncing the mining pool or checking the height for the pool like this?
sync:start().
or this?
api:height().

I mined a few blocks, and I thought I could confirm the pool by checking the height or your light wallet web page. The height shown on your light node (wallet web page) didn't change, so I'm not sure how to confirm my pool is syncing correctly.

Thank you for any advise you have on this.

**Comment by zack-bitcoin** [comment]
If you run mining pool software on a computer and you are not running an amoveo full node on that computer, then you will be unable to mine.

First turn on amoveo, then turn on the mining pool.

It doesn't matter whether the pool is on or off. You  sync the amoveo node the same way.

**Comment by Mandelhoff** [comment]
Thank you. Running the full node and then the mining pool seems to work for remote mining via port 8085. I able to poll work and submit results remotely.

When it says "Found Block", should that make the height increase or what other sort of success confirmation can I check?

The local miner (going directly to the full node via port 8081) finds blocks too but doesn't increase the height, so that may not be something I should expect. Thank you for helping clarify this.

**Comment by zack-bitcoin** [comment]
If 2 nodes find blocks at the same height at the same time, only one of them will be valid. 

You can only access port 8081 if the miner is running on the same computer as the amoveo full node.

I am certain that 8081 works because none of this code has changed in 2 weeks, and this is how I usually mine blocks since it is the fastest way.

**Comment by Mandelhoff** [comment]
Ok, I'll start over with a new full node since local mining isn't working for me either. Likely not a "pool" issue if local mining is failing for me too.

**Comment by zack-bitcoin** [comment]
There is a problem where if you try doing "make prod-restart" when it is already turned on, it will corrupt the database and cause problems like you describe.
Or if you turn it off with control+C, that can cause a similar problem.

This failure mode is bad because it is so silent. It isn't obvious what went wrong.

**Comment by Mandelhoff** [comment]
That was likely the cause. I did plenty of control+C then 'a' for abort to exit the erlang prompt. I'm sure I've tried the "make prod-restart" too, but that was probably after already doing many control+C exits.

**Comment by zack-bitcoin** [comment]
`api:off().` is the correct way to shut it off.

I am not sure how to disable control+c from the erlang shell.

Most users wont ever have to touch the erlang shell, they will use the api to talk to the blockchain. So maybe this isn't important to fix.
