### ISSUE TITLE
config.erl changes didnt not applied 

### ISSUE THREAD

**Issue by ghost** [zack-bitcoin/amoveo-mining-pool#10]
sry , 
steps to copy issue
- start.sh 
- halt
- config.erl changed
- start.sh 
config.erl changes didnt not applied 

i send u my veo, pls sent 
BJTCVI 。。。
srcy my english thnk u my veo

**Comment by zack-bitcoin** [comment]
In order to turn it off, you first need to attach to the erlang process with `sh attach.sh`

Then you can issue the halt command to erlang: `halt().`

Then edit config.erl.
then do `start.sh`

ok, you want me to send the Veo to BJTCVISLqHB4LAABHuh+tgnS03zWUubESv2dioT9TtqzA1lLHq7bUpexDHrm6JFTLe2GtU3Ea/4q+ZpA2mDbKHg= correct?
You are sure that you still have the private key?

**Comment by zack-bitcoin** [comment]
Looks like you sent me this much.
0.95565326

I guess this happened because you couldn't update the public key in the config.erl file.

I will send back 0.954 since I wont pay your tx fee.
Just double-check that you still have the private key for your account, and I will send.

**Comment by zack-bitcoin** [comment]
@triedtomine please confirm that you still control that public key so that I can send you your refund of 0.95565326

**Comment by ghost** [comment]
I control.

**Comment by zack-bitcoin** [comment]
done.
