### ISSUE TITLE
Pool Response to Found Block [-6, 105, ...]

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo-mining-pool#3]
I submitted some found blocks to my pool and got a strange response. See the line of [-6, 105, 110, ...] as the pool's response:

![image](https://user-images.githubusercontent.com/35471470/35332275-1a211464-00d0-11e8-9d87-af168eeb7f12.png)

Any ideas why this happens?
Thank you.

**Comment by zack-bitcoin** [comment]
I don't use windows. I have never seen any amoveo code say "Press any key to continue".

Getting erlang-amoveo to work in Windows is not a goal of this project.
99.99% of users will only use the light node in the browser.

The thing you are pointing at is a list of integers. 
This list of integers only uses integers that are valid byte representation of ascii text.
It is saying "invalid work".
I did this at the erlang prompt:

Eshell V8.3  (abort with ^G)
1> <<105,110,118,97,108,105,100,32,119,111,114,107>>.
<<"invalid work">>
2> 

I don't know why this is happening for you in windows. It is different from the messages I get in Linux.

**Comment by Mandelhoff** [comment]
Thank you for indicating it's "invalid work".

I've been working on a miner built with Visual Studio on Windows that uses RestCPP and internal threads rather than having the erlang process wrapper. I have not optimized the mining functions yet - mostly just working on the threading and Rest endpoints to match what the pool expects.

**Comment by zack-bitcoin** [comment]
The goal of your effort is to let people easily install a miner without first installing erlang?
Maybe an easier way to achieve the same goal would be to wrap up the erlang code into a release, so that it can be easily installed to windows in one step without dependencies. 

Or maybe it would be better to upgrade the javascript miner to use web assembly. Then you could mine from the browser as quickly as the C miner.

Soon we will upgrade to GPU mining, so all the CPU mining code will be obsolete.
Maybe we should forget making CPU miners, and move our focus to GPU.

**Comment by Mandelhoff** [comment]
No big clear goals - just trying to work on something in C++ and get the miner to run on Windows with Visual Studio (with some optimizations: Rest, Multi-threads, etc..).

I'll take a peek a  CUDA for GPU, but I don't know any CUDA yet.

**Comment by Mandelhoff** [comment]
I found my bug. I was hashing the difficulty incorrectly.

I had changed it to be like this:
	sha256_update(&ctx, &difficulty, 2);

And that's not the same as this:
	text[32] = difficulty / 256;
	text[33] = difficulty % 256;

**Comment by zack-bitcoin** [comment]
I think OpenCL might be better than CUDA.
It seems like other GPU miners have had more success with OpenCL than CUDA.
